### PR TITLE
Danetsao 02 basic ux

### PR DESCRIPTION
**Pull request by danetsao**

### CODE REVIEW

**Review by ncovercash — APPROVED** [review]
Looks good! Any questions?

**Comment by ncovercash** [comment]
Also please request reviews from @nhanaa , too

**Comment by danetsao** [comment]
Ok, sounds good. No questions so far.

**Comment by sjturner-ua** [comment]
Great progress, guys, Dane! Thank you Noah, for continuing to work with us so closely.

S

**Review by nhanaa — APPROVED** [review]

**Pull request merged**
